//! Pure and simple Vulkan bindings generated from Vulkan-Headers!
//!
//! Mira provides a simple and straightforward way to interact with Vulkan.
//! Everything was generated by bindgen and uses the original API names.
//! This crate provides:
//! * Function pointers!
//! * Dynamic loader of instance and device commands!
//! * Original names of commands, structures and macros!
//! * Extra useful features to help with development!
//! * Simple examples!

pub mod vulkan;
pub mod loader;
pub mod mem;
pub mod error;
