//! Pure and simple Vulkan bindings generated from Vulkan-Headers!
//!
//! Mira provides a simple and straightforward way to interact with Vulkan.
//! Everything was generated by bindgen and uses the original API names.
//! This crate provides:
//! * :eyes: Function pointers!
//! * :100: Dynamic loader of instance and device commands!
//! * :writing_hand: Original names of commands, structures and macros!
//! * :muscle: Extra useful features to help with development!
//! * :grinning: Simple examples!

pub mod vulkan;
pub mod loader;
pub mod mem;

