//! # mira
//! [![crates.io](https://img.shields.io/crates/v/mira.svg)](https://crates.io/crates/mira)
//! [![docs.rs](https://docs.rs/mira/badge.svg)](https://docs.rs/mira)
//! [![license](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://www.apache.org/licenses/LICENSE-2.0)
//!
//! Pure and simple Vulkan bindings generated from Vulkan-Headers!
//!
//! Mira provides a simple and straightforward way to interact with Vulkan.
//! Everything was generated by bindgen and uses the original API names.
//!
//! This crate provides:
//! * 👀 Raw function pointers!
//! * 💯 Dynamic loader of instance and device commands!
//! * ✍️ Original names of commands, structures and macros!
//!
//! ## Examples
//! Successfully tested on Linux(Lubuntu 20.04) with Intel(R) HD Graphics 620 (KBL GT2).
//! <br><br>
//!
//! ### Color
//! Displays a window with a purple background.
//! ```bash
//! cargo run --example color
//! ```
//!
//! ![screenshot](https://github.com/onlymaresia/mira/raw/HEAD/examples/mira_color.png)
//! <br><br>
//!
//! ## Vulkan version
//! 1.3.302 (with av1, h264 and h265 video extensions)
//! 
//! For a version in sync with the official vulkan headers repository clone this
//! project from github and run the generator.
//!
//! [Vulkan Changelog](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/ChangeLog.adoc)
//! <br><br>
//!
//! ## License
//!
//! [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
//! <br><br>

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub mod error;
pub mod loader;
pub mod mem;
pub mod version;
pub mod vulkan;
